# -*- coding: utf-8 -*-
"""Health Sciences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tDAPi0V6HMqUxiemV4u6wGgLU5NqLL3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('/content/HealthSciences_Dataset.xlsx', 'data')
df

df.shape

plt.hist(df['age'], align = 'left')
plt.show()

race_dict = {}

for i in df['race']:
  if i not in race_dict:
    race_dict[i] = 1
  else:
    race_dict[i] += 1

race_dict

plt.bar(race_dict.keys(),race_dict.values())
plt.show()

gender_dict = {}

for i in df['gender']:
  if i not in gender_dict:
    gender_dict[i] = 1
  else:
    gender_dict[i] += 1

gender_dict

plt.bar(gender_dict.keys(), gender_dict.values())
plt.show()

bins = range(1, 14)
plt.hist(df['time_in_hospital'], align = 'left', bins = bins)
plt.show()

plt.hist(df['weight'], align = 'left')
plt.show()

weight_dict = {}

for i in df['weight']:
  if i not in weight_dict:
    weight_dict[i] = 1
  else:
    weight_dict[i] += 1

weight_dict

columns = df.columns
columns

treatments = columns[22:47]
treatments

for i in treatments:
  treatment_dict = {}
  for x in df[i]:
    if x not in treatment_dict:
      treatment_dict[x] = 1
    else:
      treatment_dict[x] += 1

  print(f'{i}:')
  print(treatment_dict)
  print(f'{sum(treatment_dict.values())}\n')

code_dict = {}
for i in df['diag_1']:
  if i not in code_dict:
    code_dict[i] = 1
  else:
    code_dict[i] += 1

print(len(code_dict.keys()))

plt.scatter(df['time_in_hospital'], df['number_diagnoses'])
plt.xlabel('Time in Hospital (Days)')
plt.ylabel('Number of Diagnoses')
plt.show()

len(df['diag_3'].unique())

df.sort_values('time_in_hospital', ascending = True)

payer_dict = {}

for i in df['payer_code']:
  if i not in payer_dict:
    payer_dict[i] = 1
  else:
    payer_dict[i] += 1

payer_dict

plt.bar(payer_dict.keys(), payer_dict.values())
plt.show()

payer_dict = dict(reversed(sorted(payer_dict.items(), key=lambda item: item[1])))

plt.bar(payer_dict.keys(), payer_dict.values())
plt.show()

med_dict = {}

for i in df['medical_specialty']:
  if i not in med_dict:
    med_dict[i] = 1
  else:
    med_dict[i] += 1

med_dict

med_dict = dict(reversed(sorted(med_dict.items(), key=lambda item: item[1])))

plt.bar(list(med_dict.keys())[:10], list(med_dict.values())[:10])
plt.xticks(list(med_dict.keys())[:10], rotation=90)
plt.show()

bins = range(1, 10)
plt.hist(df['admission_type_id'], align = 'left', bins = bins, rwidth = 0.8)
plt.show()

asian_df = df[df['race'] == 'asian']
bins = range(1, 11)

plt.hist(df['number_diagnoses'], align = 'left', bins = bins, rwidth = 0.8)
plt.xlabel("Number of Asian Patients' Diagnoses")
plt.ylabel('Frequency')
plt.show()

# Right now I'm considering doing a predictive model, right?
# One that predicts the number of diagnoses
# Based on the factors we think are correlated

# Maybe say the model can estimate your risk of diabetes, usually for old people?
# Cause most of the people were [70 - 80) +
# Nostalgia cause old people lmao

# Alright maybe nostalgia because it helps us predict how susceptible our close family is to diabetes
# Makes us enjoy our time with them now more
# Nostalgia?

